execution:
  env: "dev"
  tags: []
  default_suite: "core"
  parallel:
    enabled: true
    workers: 2
    dist_mode: "file"
  retry:
    enabled: true
    max_reruns: 2
    reruns_delay: 1
    only_flaky: false

paths:
  cookie_dir: "common"

allure:
  enabled: true
  results_dir: "allure-results"
  report_dir: "allure-report"
  clean_results: true
  open_report: true
  report_title: "知末网自动化测试报告"

environments:
  dev:
    base_url: "https://www.znzmo.com/?from=personalCenter"
    headless: false
    default_timeout_ms: 30000
    browser:
      name: "chromium"
      channel: "chrome"
      slow_mo_ms: 0
      launch_args: []
  test:
    base_url: "https://example.com"
    headless: false
    default_timeout_ms: 12000
    browser:
      name: "chromium"
      channel: ""
      slow_mo_ms: 0
      launch_args: []
  prod:
    base_url: "https://example.com"
    headless: false
    default_timeout_ms: 15000
    browser:
      name: "chromium"
      channel: ""
      slow_mo_ms: 0
      launch_args: []
